# Generated by Django 4.1 on 2022-08-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='edad',
            new_name='numpreferido',
        ),
    ]
