# Generated by Django 4.1 on 2022-09-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_curso_estudiante_profesor_delete_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('texto', models.TextField()),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
    ]
