# Generated by Django 4.1 on 2022-09-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_contacto_delete_curso_delete_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia']]),
        ),
    ]
