# Generated by Django 4.1 on 2022-10-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
